[package]
name = "shadplay"
version = "0.0.1"
resolver = "2"
edition = "2021"
authors = ["jeremy webb <alphastrata@gmail.com>"]
license = "MIT"
description = """
Shadplay is a simple, (WIP) application that provides a window where shader code is applied to Bevy mesh geometry. The primary goal of shadplay is to allow users to see immediate changes to their shader code. This is achieved by leveraging Bevy's file-watcher system, which automatically recompiles and updates the shader on the mesh whenever the user saves their changes in their editor of choice. shadplay is designed to provide the lowest barrier to entry for individuals who want to learn or practice using WGSL (WebGPU Shading Language) for the purposes of doing work in Bevy.
"""

[features]
default = ["ui"]
wayland = []
ui = []

[dependencies]
bevy = { version = "0.12.0", features = [
  "file_watcher",
  "dynamic_linking",
  "wayland",
  "jpeg",
] }
bevy_egui = { git = "https://github.com/raffaeleragni/bevy_egui", branch = "bevy_0_12" } #, version = "0.22.0" }
bevy_panorbit_camera = { git = "https://github.com/Plonq/bevy_panorbit_camera", branch = "bevy-0.12" } #, version= "0.9.0"}
chrono = "0.4.31"
copypasta = "0.10.0"
directories = "5.0.1"
serde = { version = "1.0.190", features = ["derive"] }
toml = "0.8.6"

[profile.dev] # A little bit of optimisation for dev builds
opt-level = 1

[profile.dev.package."*"] # Always build dependencies with the highest level of optimisations possible.
opt-level = 3

[build-dependencies]
glob = "0.3.1"
