[package]
name = "pally_aura"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*", features = ["file_watcher", "dynamic_linking", "jpeg"] }
bevy_editor_pls = "0.6.0"
bevy_panorbit_camera = "0.9.0"


[dev-dependencies.bevy]
opt-level = 3
